
export default {
    VITE_SERVICE_NAME: import.meta.env.VITE_SERVICE_NAME || "",
    VITE_FIREBASE_APIKEY: import.meta.env.VITE_FIREBASE_APIKEY,
    VITE_FIREBASE_AUTHDOMAIN: import.meta.env.VITE_FIREBASE_AUTHDOMAIN,
    VITE_FIREBASE_DATABASEURL: import.meta.env.VITE_FIREBASE_DATABASEURL,
    VITE_FIREBASE_PROJECTID: import.meta.env.VITE_FIREBASE_PROJECTID,
    VITE_FIREBASE_STORAGEBUCKET: import.meta.env.VITE_FIREBASE_STORAGEBUCKET,
    VITE_FIREBASE_MESSAGINGSENDERID: import.meta.env.VITE_FIREBASE_MESSAGINGSENDERID,
    VITE_FIREBASE_APPID: import.meta.env.VITE_FIREBASE_APPID,
    VITE_FIREBASE_MEASUREMENTID: import.meta.env.VITE_FIREBASE_MEASUREMENTID,
}